import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Sidebar from "./components/Sidebar";
import NavTabs from "./components/NavTabs";
import Maincontent from "./components/Maincontent";
import Shorts from "./components/Shorts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` max-w-screen hide-scrollbar geistsans bg-black h-auto ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen w-full bg-black text-white font-roboto">
          {/* Header Section */}
          <Navbar />

          <main className="w-full h-auto flex">
            {/* Sidebar Section */}
            <aside className="w-[6%] z-[3000] hidden fixed bg-black top-14 border-r border-[#303030] lg:flex flex-col items-center py-4 h-screen">
              <Sidebar />
            </aside>

            {/* Main Content Section */}
            <div className="flex-1 max-w-full hide-scrollbar h-auto lg:ml-[6%]">
              {children}
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
