import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Sidebar from "./components/Sidebar";
import NavTabs from "./components/NavTabs";
import Maincontent from "./components/Maincontent";
import Shorts from "./components/Shorts";
import { Providers } from "./Providers";
import Content from "./components/Content";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` max-w-screen hide-scrollbar geistsans bg-black h-auto ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="min-h-screen w-full bg-black text-white font-roboto">
            {/* Header Section */}
            <Navbar />

            <main className="w-full h-auto flex">
              {/* Sidebar Section */}
              <Sidebar />

              {/* Main Content Section */}
              <Content children={children} />
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
